views/home.py
from flask import Flask, redirect, render_template, url_for, session, jsonify, flash, Blueprint
from flask_login import current_user, login_required
from models import db, User_schema, Users_schema, Racquet_schema, Racquets_schema, Racquets

homes = Blueprint("home", __name__, url_prefix="")

@homes.route("/home", methods=["POST", "GET"])
@login_required
def home():
    
    if current_user.paid == False:
        flash("You must pay before accessing your API Key", "danger")
        return redirect(url_for('checkout'))
    return render_template("home.html")

templates/checkout.html
{% extends 'layout.html' %}

{% block body %}
<!-- flash messages -->
<div style="position:fixed; left:25%; top:2%;z-index:9999;" class="container w-50 text-center">{% with messages = get_flashed_messages(with_categories=true)%}
    {% if messages %}
        {% for category, msg in messages %}
        <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
          {{msg}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}
  {% endwith%}</div>

<div class="container-fluid p-5">
    <div class="container rounded shadow p-3 bg-light">
        <div class="text-center">
            <div class="p-3">
                <h1 class="fw-bold">
                    Last step is to pay to gain access.
                </h1>
            </div>
            <div class="text-center p-5">
                <i class="fa-solid fa-cart-shopping fa-10x"></i> 
            </div>
            <div>
                <form action="/create-checkout-session" method="POST">
                    <button type="submit" class="bttn-jelly bttn-md bttn-primary bg-secondary">Checkout</button>
                  </form>
            </div>
        </div>
    </div>
   
</div>
{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block body %} 
<!-- flash messages -->
<div style="position:fixed; left:25%; top:2%;z-index:9999;" class="container w-50 text-center">{% with messages = get_flashed_messages(with_categories=true)%}
  {% if messages %}
      {% for category, msg in messages %}
      <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
        {{msg}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
  {% endif %}
{% endwith%}</div>
<div class="bg-dark" style="min-height:80vh">



<!-- nav -->
    <div class="pt-2 bg-dark">
        <ul class="nav justify-content-center">
          <li class="nav-item">
            <a class="nav-link nav-item-link" aria-current="page" href="{{url_for('home.home')}}"
              >Home</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link nav-item-link" href="#">Documentation</a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-item-link" href="#developer-container">My Account</a>
          </li>
          <li class="nav-item">
          </li>
          <li class="nav-item">
            <a href="{{url_for('logout')}}"><button class=" ms-2 btn-out-primary">Logout</button></a>
          </li>
        </ul>
      </div>
    
    <!-- content -->
    <div class="container-fluid text-center p-4">
        <h1 class="fw-bold">
            <span class="text-primary-light">T</span><span class="text-secondary-light">E</span><span class="text-primary-light">N</span><span class="text-secondary-light">N</span><span class="text-primary-light">I</span><span class="text-secondary-light">S</span><span class="text-primary-light"> A</span><span class="text-secondary-light">P</span><span class="text-primary-light">I</span>
        </h1>
    </div>
    <div class="container ps-5 pb-3 text-light">
      <h1 class="fw-bold">Welcome {{current_user.name}}</h1>

    </div>

<div class="container-fluid mb-4">
    <div class="row justify-content-center">
        <div class="col-lg-3 col-md-4 p-3">
            <div class="p-3 bg-light shadow rounded" style="min-height: 250px;">
                <h4 class="fw-bold">Getting Started</h4>
                <p>Here you can view your API Key to send POST/GET requests</p><br>
                <p class="h5 fw-bold">API KEY:</p>
                <p>{{current_user.key}}</p>
            </div>
        </div>
        <div class="col-lg-3 col-md-4 p-3">
            <div class="p-3 shadow rounded text-dark bg-secondary-light" style="min-height: 250px; position:relative;">
                <h4 class="fw-bold">Documentation</h4>
                <p>
                    Most of th API is fairly intuitive. Though, many of the calls will need instructions.
                </p>
                <div class="text-center mt-5">
                    <button class="bttn-jelly bttn-md bttn-primary bg-primary-light text-dark">
                        View Instructions
                      </button>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-4 p-3">
            <div class="p-3 shadow rounded text-dark bg-primary-light" style="min-height: 250px;">
                <h4 class="fw-bold">Requests Remaining</h4>
            </div>
        </div>
    </div>
</div>
</div>

<!-- footer -->
<div class="bg-footer" style="min-height: 20vh;">
  <div class="container-fluid p-3 border-bottom border-secondary">
    <div class="row justify-content-center">
      <div class="col-md-4 text-center">
        <p>Get connected with us on social networks:</p>
      </div>
      <div class="col-md-4 d-inline text-center">
        <div class='d-inline'>
          <a href="" class="text-dark"><i class="fa-brands fa-facebook fa-2x"></i></a>
        </div>
        <div class='d-inline ms-5'>
          <a href="" class="text-dark"><i class="fa-brands fa-instagram fa-2x"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center pt-5 pb-3">
    <div class="col-sm-2 ms-4 text-start">
      <p class="fw-bold">TENNIS API</p>
      <p>leader in tennis information</p>
    </div>
    <div class="col-sm-2 ms-4 text-start mb-3">
      <p class="fw-bold">USEFUL LINKS</p>
      <a href="">Link 1</a><br>
      <a href="">Link 2</a><br>
      <a href="">Link 3</a>
    </div>
    <div class="col-sm-2 ms-4 text-start">
      <p class="fw-bold">CONTACT</p>
      <span><i class="fa fa-phone" aria-hidden="true"></i></span><span> 3076307030</span><br>
      <span><i class="fa fa-mail-bulk" aria-hidden="true"></i></span><span> jacobglapkin@gmail.com</span><br>
      <span><i class="fas fa-search-location    "></i></span><span> Redondo Beach, CA 90277</span>

    </div>
  </div>
</div>

{% endblock %}

templates/index.html
{% extends "layout.html" %} {% block body %}
  <!-- flash messages -->
  <div style="position:fixed; left:25%; top:2%;z-index:9999;" class="container w-50 text-center">{% with messages = get_flashed_messages(with_categories=true)%}
    {% if messages %}
        {% for category, msg in messages %}
        <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
          {{msg}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}
  {% endwith%}</div>

<div class="container-fluid text-center main-jumbo shadow" style="min-height: 30vh;">
  <div class="pt-2">
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link nav-item-link" aria-current="page" href="#why-container"
          >Why</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link nav-item-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-item-link" href="#developer-container">Quotes</a>
      </li>
      <li class="nav-item">
        <button class=" ms-2 btn-out-primary" data-bs-toggle="modal" data-bs-target="#LoginModal">Login</button>
      </li>
    </ul>
  </div>

  <div class="container-fluid jumbo-content">
    <h1 class="text-light fw-bold jumbo-header">Welcome to Tennis API</h1>
    <div class="text-center text-light pt-2 ps-5 pe-5">
      <h5>
        Go further in your tennis game with the #1 trusted leader in tennis
        information
      </h5>
    </div>
  </div>
  <div class="text-center pb-5">
    <a href="{{url_for('registering')}}"><button class="bttn-jelly bttn-md bttn-primary bg-primary-light text-dark">
      Register
    </button></a>
  </div>
</div>



<!-- after jumbo -->
<div id="why-container" class="container-fluid pt-5 pb-5" style="min-height: 20vh;">
  <div class="text-center">
    <h2 class="fw-bold">Why Tennis API?</h2>
    <div class="ps-3 pe-3">
      <p>
        Whether your a developer or an active member of the tennis community,
        <br />
        having greater access to tennis information is key.
      </p>
    </div>
  </div>

  <!-- Slider main container -->
<div class="swiper">
  <!-- Additional required wrapper -->
  <div class="swiper-wrapper">
    <!-- Slides -->
    <div class="swiper-slide equipment-widget">
      <div class="ps-4 pt-4">
        <h1 class="fw-bold text-light">Equipment</h1>
      </div>
    </div>
    <div class="swiper-slide scores-widget">
      <div class="ps-4 pt-4">
        <h1 class="fw-bold text-light">ATP Information</h1>
      </div>
    </div>
    <div class="swiper-slide atp-widget">
      <div class="ps-4 pt-4">
        <h1 class="fw-bold text-light">Scores</h1>
      </div>
    </div>
  </div>
  <!-- If we need pagination -->
  <div class="swiper-pagination"></div>

  <!-- If we need navigation buttons -->
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>


</div>

  
</div>
<div id="developer-container" class="container-fluid bg-secondary" style="min-height: 30vh;">
  <div class="pt-5 pb-5 pr-4 pl-4">
    <div class="text-center text-light pt-3 pb-3">
      <h2 class="fw-bold">Developers Love Tennis API</h2>
    </div>
    <div class="container-fluid border-bottom border-top">
      <div data-aos="fade-right" class="row justify-content-center text-light">
        <div class="col-md-3 col-lg-4 p-4">
          <p>
            " Lorem ipsum, dolor sit amet consectetur adipisicing elit.
            Voluptas, nihil distinctio? Quam, omnis itaque harum earum totam
            blanditiis, delectus consectetur corporis esse odit corrupti.
            Dignissimos illum voluptates nesciunt. Repellat, nemo. "
          </p>
          <small>Jacob - Irvine, CA</small>
        </div>
        <div class="col-md-3 col-lg-4 p-4">
          <p>
            " Lorem ipsum, dolor sit amet consectetur adipisicing elit.
            Voluptas, nihil distinctio? Quam, omnis itaque harum earum totam
            blanditiis, delectus consectetur corporis esse odit corrupti.
            Dignissimos illum voluptates nesciunt. Repellat, nemo. "
          </p>
          <small>-Julia - Redondo Beach, CA</small>
        </div>
        <div class="col-md-3 col-lg-4 p-4">
          <p>
            " Lorem ipsum, dolor sit amet consectetur adipisicing elit.
            Voluptas, nihil distinctio? Quam, omnis itaque harum earum totam
            blanditiis, delectus consectetur corporis esse odit corrupti.
            Dignissimos illum voluptates nesciunt. Repellat, nemo. "
          </p>
          <small>Daniel - Palo Alto, CA</small>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid pb-5 pt-3">
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-5">
        <div class="p-5 text-center shadow rounded bg-light" data-aos="fade-up">
          <h1>stat</h1>
        </div>
        <div class="p-5 text-center shadow rounded bg-primary-light mt-4" data-aos="fade-up">
          <h1>stat</h1>
        </div>
      </div>
      <div class="col-md-6 col-lg-5 mt-4">
        <div class="p-5 text-center shadow rounded bg-primary-light" data-aos="fade-up">
          <h1>stat</h1>
        </div>
        <div class="p-5 text-center shadow rounded bg-light mt-4" data-aos="fade-up">
          <h1>stat</h1>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- login modal  -->
<!-- Modal -->
<div class="modal fade" id="LoginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content modal-style">
      <div class="modal-body">
        <button type="button" class="btn-close float-end" data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="text-center">
          <h2 class="fw-bold">Login</h2>
        </div>
        <div>
          <form class="form needs-validation" novalidate method="POST" action="{{url_for('index')}}" enctype="multipart/form-data">
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Email address</label>
              <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" required>
              <div class="invalid-feedback">
                Please provide a valid email format.
              </div>
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" name="password" class="form-control" id="exampleInputPassword1" required>
            </div>
            <div class="text-center">
              <button type="submit" class="bttn-jelly bttn-md bttn-primary bg-secondary">Login</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- footer -->
<div class="bg-footer">
  <div class="container-fluid p-3 border-bottom border-secondary">
    <div class="row justify-content-center">
      <div class="col-md-4 text-center">
        <p>Get connected with us on social networks:</p>
      </div>
      <div class="col-md-4 d-inline text-center">
        <div class='d-inline'>
          <a href="" class="text-dark"><i class="fa-brands fa-facebook fa-2x"></i></a>
        </div>
        <div class='d-inline ms-5'>
          <a href="" class="text-dark"><i class="fa-brands fa-instagram fa-2x"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center pt-5 pb-3">
    <div class="col-sm-2 text-start">
      <p class="fw-bold">TENNIS API</p>
      <p>leader in tennis information</p>
    </div>
    <div class="col-sm-2 text-start">
      <p class="fw-bold">USEFUL LINKS</p>
      <a href="">Link 1</a><br>
      <a href="">Link 2</a><br>
      <a href="">Link 3</a>
    </div>
    <div class="col-sm-2 text-start">
      <p class="fw-bold">CONTACT</p>
      <span><i class="fa fa-phone" aria-hidden="true"></i></span><span> 3076307030</span><br>
      <span><i class="fa fa-mail-bulk" aria-hidden="true"></i></span><span> jacobglapkin@gmail.com</span><br>
      <span><i class="fas fa-search-location    "></i></span><span> Redondo Beach, CA 90277</span>

    </div>
  </div>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/main.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bttn.css/0.2.4/bttn.min.css" integrity="sha512-/2285SnGiTHjSKBkJzedsJ8wwSP0j74ZQyusMQ9j5Z1RtyKqZ3XtfS8hVp8OadLs2uq+8V6/n+CyqUNTO/UpYg==" crossorigin="anonymous" referrerpolicy="no-referrer" /></head>
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link
  rel="stylesheet"
  href="https://unpkg.com/swiper@8/swiper-bundle.min.css"
/>

<script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
<body>
    {% block body %}
    
    
    {% endblock %}
    <script src="{{url_for('static', filename='js/scripts.js')}}"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init();
      </script>

      <!-- bootstrap form validatoin -->
      <script>
          // Example starter JavaScript for disabling form submissions if there are invalid fields
(function () {
    'use strict'
  
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.querySelectorAll('.needs-validation')
  
    // Loop over them and prevent submission
    Array.prototype.slice.call(forms)
      .forEach(function (form) {
        form.addEventListener('submit', function (event) {
          if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
          }
  
          form.classList.add('was-validated')
        }, false)
      })
  })()
      </script>


</body>
</html>

templates/registering.html
{% extends "layout.html" %}

{% block body %}
<!-- flash messages -->
<div style="position:fixed; left:25%; top:2%;z-index:9999;" class="container w-50 text-center">{% with messages = get_flashed_messages(with_categories=true)%}
  {% if messages %}
      {% for category, msg in messages %}
      <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
        {{msg}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
  {% endif %}
{% endwith%}</div>
<div class="container-fluid p-5">
    <div class="container rounded shadow p-3">
        <div class="text-center p-3">
            <h1 class="fw-bold">Register</h1>
        </div>
        <div style="max-width: 500px;margin:auto;">
            <form class="form needs-validation" novalidate method="POST" action="{{url_for('registering')}}" enctype="multipart/form-data">
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Name</label>
                    <input type="text" name="reg-name" class="form-control" id="exampleInputPassword1" required>
                  </div>
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">Email address</label>
                  <input type="email" class="form-control" name="reg-email" id="exampleInputEmail1" aria-describedby="emailHelp" required>
                  <div class="invalid-feedback">
                    Please provide a valid email format.
                  </div>
                  <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">Password</label>
                  <input type="password" name="reg-password" class="form-control" id="exampleInputPassword1" required>
                </div>
                <div class="text-center">
                  <button type="submit" class="bttn-jelly bttn-md bttn-primary bg-secondary">Register</button>
                </div>
              </form>
        </div>
    </div>
   
</div>

{% endblock %}

templates/success.html
{% extends 'layout.html' %}

{% block body %}

    <h1>Thanks for your order!</h1>
    <p>
      We appreciate your business!
      If you have any questions, please email
      <a href="mailto:orders@example.com">orders@example.com</a>.
    </p>

{% endblock %}